version: 0.2

phases:
  install:
    commands:
      - choco install cyg-get -y --no-progress
      - cyg-get bash patch bison flex make wget
      - dir 'C:\ProgramData\chocolatey\lib\Cygwin\tools\cygwin'
      - dir 'C:\ProgramData\chocolatey\lib\Cygwin\tools\cygwin\bin'
      - dir 'C:\Program Files (x86)'
      - 'C:\ProgramData\chocolatey\lib\Cygwin\tools\cygwin\bin\bash -c "make -C src"'
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
cache:
  paths:
