version: 0.2

phases:
  install:
    commands:
      - choco install cyg-get -y --no-progress
      - cyg-get bash patch bison flex make wget
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
cache:
  paths:
