version: 0.2

phases:
  install:
    commands:
      - choco install wget -y --no-progress
      - choco install gnuwin32-make.portable -y --no-progress
      - choco install cmake -y --no-progress
      - choco install winflexbison3 -y --no-progress
  build:
    commands:
      - cd src
      - make
  post_build:
    commands:
artifacts:
  files:
cache:
  paths:
