version: 0.2

phases:
  install:
    commands:
      - choco install cyg-get -y --no-progress
      - cyg-get bash patch bison flex make wget
      - dir 'C:\tools\cygwin'
      - dir 'C:\tools\cygwin\bin'
      - dir 'C:\Program Files (x86)'
      - 'C:\tools\cygwin\bin\sed -i "s/BUILD_ENV[ ]*=.*/BUILD_ENV = MSVC/" src/config.inc'
      - 'C:\tools\cygwin\bin\bash -login -c "set"'
      - 'C:\tools\cygwin\bin\bash -login -c "/bin/make -C src DOWNLOADER=wget minisat2-download"'
      - 'C:\tools\cygwin\bin\bash -login -c "/bin/make -C src"'
      - 'C:\tools\cygwin\bin\bash -login -c "/bin/make -C jbmc/src"'
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
cache:
  paths:
