version: 0.2

phases:
  install:
    commands:
      - choco install wget gnuwin32-make.portable winflexbison3 -y --no-progress
  build:
    commands:
      - cd src
      - 'C:\ProgramData\chocolatey\lib\gnuwin32-make.portable\tools\bin\make'
  post_build:
    commands:
artifacts:
  files:
cache:
  paths:
